/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TestLazyImport = createFileRoute('/test')()
const MapLazyImport = createFileRoute('/map')()
const BLazyImport = createFileRoute('/b')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TestLazyRoute = TestLazyImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))

const MapLazyRoute = MapLazyImport.update({
  path: '/map',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/map.lazy').then((d) => d.Route))

const BLazyRoute = BLazyImport.update({
  path: '/b',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/b.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/b': {
      id: '/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof BLazyImport
      parentRoute: typeof rootRoute
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapLazyImport
      parentRoute: typeof rootRoute
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/b': typeof BLazyRoute
  '/map': typeof MapLazyRoute
  '/test': typeof TestLazyRoute
}

interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/b': typeof BLazyRoute
  '/map': typeof MapLazyRoute
  '/test': typeof TestLazyRoute
}

interface FileRoutesById {
  '/': typeof IndexLazyRoute
  '/b': typeof BLazyRoute
  '/map': typeof MapLazyRoute
  '/test': typeof TestLazyRoute
}

interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/b' | '/map' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/b' | '/map' | '/test'
  id: '/' | '/b' | '/map' | '/test'
  fileRoutesById: FileRoutesById
}

interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  BLazyRoute: typeof BLazyRoute
  MapLazyRoute: typeof MapLazyRoute
  TestLazyRoute: typeof TestLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  BLazyRoute: BLazyRoute,
  MapLazyRoute: MapLazyRoute,
  TestLazyRoute: TestLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/b",
        "/map",
        "/test"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/b": {
      "filePath": "b.lazy.tsx"
    },
    "/map": {
      "filePath": "map.lazy.tsx"
    },
    "/test": {
      "filePath": "test.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
